config/routes.rb
Rails.application.routes.draw do
  resources :tickets do
    member do
      post :update_state
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "tickets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  enum :state, %i[backlog next in_progress done], default: :backlog

  validates_presence_of :title, :description

  after_update_commit -> { broadcast_refresh_later_to("main-board") }
  after_create_commit  -> { broadcast_refresh_later_to("main-board") }
  after_destroy_commit -> { broadcast_refresh_later_to("main-board") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update update_state destroy ]

  def index
    @tickets = Ticket.all.group_by(&:state)
    @new_ticket = Ticket.new
  end

  def show
  end

  def new
    @ticket = Ticket.new(state: params[:state])
  end

  def edit
  end

  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      flash.notice = "Ticket was successfully created"
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to @ticket }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket, notice: "Ticket was successfully updated", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def update_state
    @ticket.update(state: params.require(:state))
    redirect_back_or_to root_path
  end

  def destroy
    @ticket.destroy!
    redirect_to root_path, notice: "Ticket was successfully destroyed", status: :see_other
  end

  private

  def set_ticket
    @ticket = Ticket.find(params.expect(:id))
  end

  def ticket_params
    params.require(:ticket).permit(:title, :description, :state)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def new_ticket_dom_id(state)
    "new_ticket_with_state_#{state}"
  end
end

app/helpers/turbo_stream_actions_helper.rb
module TurboStreamActionsHelper
  def log(message)
    turbo_stream_action_tag :log, message:
  end
end
Turbo::Streams::TagBuilder.include(TurboStreamActionsHelper)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "V1" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tickets/_column.html.erb
<div
  class="flex flex-col flex-shrink-0 w-80 border
       border-gray-300 rounded-md bg-gray-50"
  data-drag-target="dropzone"
  data-ticket-state="<%= state %>"
>
  <div
    class="flex items-center justify-between p-4
          bg-white border-b border-gray-300 rounded-t-md"
  >
    <h1 class="font-bold text-xl"><%= state.humanize %> (<%= tickets.size %>)</h1>
    <%= link_to "New ticket",
        new_ticket_path(state:),
        data: {turbo_frame: new_ticket_dom_id(state)},
        class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"
    %>
  </div>

  <div id="tickets" class="p-4 text-sm">
    <%= turbo_frame_tag new_ticket_dom_id(state) %>

    <% tickets.each do |ticket| %>
      <%= render ticket %>
    <% end %>
  </div>
</div>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, class: "contents") do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <%= form.hidden_field :state %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/tickets/_notice.html.erb
<% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
<% end %>

app/views/tickets/_ticket.html.erb
<%= turbo_frame_tag ticket do %>
  <div
    id="<%= dom_id ticket, :wrapper %>"
    class="ticket-card"
    draggable="true"
    data-drag-target="draggable"
    data-action="dragstart->drag#start"
    data-change-state-url="<%= update_state_ticket_path(ticket) %>"
  >
    <p class="my-5">
      <strong class="block font-medium mb-1">Title:</strong>
      <%= ticket.title %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Description:</strong>
      <%= ticket.description %>
    </p>

    <%= link_to "Edit this ticket", edit_ticket_path(ticket), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this ticket",
                    ticket, method: :delete, data: {turbo_frame: "_top"},
                    class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"
      %>
    </div>
  </div>
<% end %>

app/views/tickets/create.turbo_stream.erb
<%= turbo_stream.refresh request_id: nil %>
<%= turbo_stream.log("LOG: Ticket ##{@ticket.id} created") %>

app/views/tickets/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing ticket</h1>

  <%= turbo_frame_tag @ticket do %>
    <div data-turbo-permanent id="<%= dom_id @ticket, :wrapper %>" class="ticket-card">
      <%= render "form", ticket: @ticket %>

      <%= link_to "Show this ticket", @ticket, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    </div>
  <% end %>
  <%= link_to "Back to tickets", tickets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tickets/index.html.erb
<%= turbo_stream_from "main-board" %>

<div class="w-full" id="page_content">
  <%= render "notice"%>

  <% content_for :title, "Tickets" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Tickets</h1>
  </div>

  <%= turbo_frame_tag @new_ticket %>

  <div class="flex flex-grow space-x-4 overflow-x-auto" data-controller="drag">
    <% Ticket.states.keys.each do |state| %>
      <%= render "column", state:, tickets: @tickets.fetch(state, []) %>
    <% end %>
  </div>
</div>

app/views/tickets/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New ticket</h1>

  <%= turbo_frame_tag new_ticket_dom_id(@ticket.state) do %>
    <div data-controller="form" class="ticket-card">
      <%= render "form", ticket: @ticket %>

      <button data-action="click->form#remove"
              class="mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium">
        Cancel
      </button>
    </div>
  <% end %>

  <%= link_to "Back to tickets", tickets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tickets/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @ticket %>

    <%= link_to "Back to tickets", tickets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>